name       : mcrypt
version    : 2.6.8
release    : 2
source     :
    - http://garr.dl.sourceforge.net/project/mcrypt/MCrypt/2.6.8/mcrypt-2.6.8.tar.gz : 5145aa844e54cca89ddab6fb7dd9e5952811d8d787c4f4bf27eb261e6c182098
license    : GPL-3.0
summary    : Mcrypt is a simple encryption program and unix crypt replacement.
description: |
    Mcrypt is a simple encryption program, intended to be replacement for the old unix crypt.
builddeps  :
    - libmcrypt
    - libmcrypt-devel
    - libmhash-devel
rundeps :
    - libmcrypt
    - libmhash
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2012-4409.patch
    %patch -p1 < $pkgfiles/security/cve-2012-4426.patch
    %patch -p1 < $pkgfiles/security/cve-2012-4527.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
