name       : mcrypt
version    : 2.6.8
release    : 3
source     :
    - https://sourceforge.net/projects/mcrypt/files/MCrypt/2.6.8/mcrypt-2.6.8.tar.gz/download : 5145aa844e54cca89ddab6fb7dd9e5952811d8d787c4f4bf27eb261e6c182098
homepage   : https://sourceforge.net/projects/mcrypt/
license    : GPL-3.0-or-later
component  : security.library
summary    : Mcrypt is a simple encryption program and unix crypt replacement
description: |
    Mcrypt is a simple encryption program, intended to be replacement for the old unix crypt.
builddeps  :
    - libmcrypt-devel
    - libmhash-devel
setup      : |
    %patch -p1 < $pkgfiles/security/cve-2012-4409.patch
    %patch -p1 < $pkgfiles/security/cve-2012-4426.patch
    %patch -p1 < $pkgfiles/security/cve-2012-4527.patch
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
